name: sample workflow

on: push

jobs:
    first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    -name: welcome massage
      run: echo "my frist Github actions job"

    -name: list files
      run: ls
      
    -name: read file
      run: cat README.md